-- ─────────────────────────────────────────────────────────────────────────
-- funymems.cc — схема базы под Supabase.
-- Выполнить целиком в Supabase → SQL Editor. Скрипт идемпотентный:
-- можно запускать повторно, ничего не потеряется.
--
-- Модель по ТЗ: заказ → оплата → отправление CDEK → трек-номер →
-- защищённая ссылка на страницу заказа → автообновление статусов.
--
-- ГЛАВНОЕ ПРО БЕЗОПАСНОСТЬ: RLS включён везде и политик для anon нет.
-- Значит из браузера напрямую читать и писать нельзя — пишет только
-- backend под service_role ключом. Покупатель видит свой заказ через
-- функцию order_by_token(), которой отдаёт секретный токен из ссылки.
-- ─────────────────────────────────────────────────────────────────────────

-- Расширения не нужны: gen_random_uuid() входит в ядро Postgres 13+,
-- а Supabase работает на 15-м. Меньше зависимостей — меньше поводов упасть.

-- ── справочник статусов ───────────────────────────────────────────────
-- Отдельными типами не делаем: расширять check-констрейнт проще, чем enum.

-- ── пользователи (на будущее) ─────────────────────────────────────────
-- Регистрации сейчас нет: заказ оформляется без аккаунта. Таблица нужна,
-- когда появится вход по номеру WhatsApp — тогда заказы свяжутся с ней.
create table if not exists public.users (
  id          uuid primary key default gen_random_uuid(),
  phone       text unique,
  name        text,
  created_at  timestamptz not null default now()
);

-- ── заказы ────────────────────────────────────────────────────────────
create table if not exists public.orders (
  id              uuid primary key default gen_random_uuid(),
  -- Человекочитаемый номер для клиента и переписки: «Заказ №10452».
  order_no        bigint generated by default as identity (start with 10452) unique,
  -- Секрет для персональной ссылки /order/<token>: 64 hex-символа.
  -- Два uuid вместо gen_random_bytes — не тянем pgcrypto и его схему.
  secure_token    text not null unique default (
                    replace(gen_random_uuid()::text, '-', '') ||
                    replace(gen_random_uuid()::text, '-', '')
                  ),
  user_id         uuid references public.users(id) on delete set null,

  -- покупатель
  customer_name   text not null,
  phone           text not null,
  whatsapp        text,
  telegram        text,

  -- доставка
  delivery_method text not null default 'courier'
                    check (delivery_method in ('courier', 'pickup')),
  city            text,
  address         text,
  comment         text,

  -- деньги, всё в тиынах не храним — суммы целые в тенге
  currency        text   not null default 'KZT',
  subtotal        bigint not null check (subtotal >= 0),
  discount        bigint not null default 0 check (discount >= 0),
  total           bigint not null check (total >= 0),
  promo_code      text,

  -- статус двигает только backend после вебхука платёжной системы
  status          text not null default 'NEW'
                    check (status in ('NEW', 'PAID', 'PACKING', 'SHIPPED', 'DELIVERED', 'CANCELLED')),
  paid_at         timestamptz,

  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index if not exists orders_created_idx on public.orders (created_at desc);
create index if not exists orders_status_idx  on public.orders (status);
create index if not exists orders_phone_idx   on public.orders (phone);

-- ── позиции заказа ────────────────────────────────────────────────────
-- Название и цену копируем в момент заказа: если потом поменяем каталог,
-- старый заказ должен остаться таким, каким его оформили.
create table if not exists public.order_items (
  id          uuid   primary key default gen_random_uuid(),
  order_id    uuid   not null references public.orders(id) on delete cascade,
  product_id  text   not null,
  title       text   not null,
  fit         text,                       -- classic | oversize
  size        text,                       -- XL | XXL
  color       text,                       -- black | white
  qty         int    not null check (qty > 0),
  unit_price  bigint not null check (unit_price >= 0),
  design      jsonb,                      -- дизайн из конструктора, если свой принт
  created_at  timestamptz not null default now()
);

create index if not exists order_items_order_idx on public.order_items (order_id);

-- ── платежи ───────────────────────────────────────────────────────────
create table if not exists public.payments (
  id                  uuid   primary key default gen_random_uuid(),
  order_id            uuid   not null references public.orders(id) on delete cascade,
  provider            text   not null,             -- kaspi, robokassa, …
  provider_payment_id text,                        -- id платежа на стороне сервиса
  amount              bigint not null check (amount >= 0),
  status              text   not null default 'PENDING'
                        check (status in ('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED')),
  raw                 jsonb,                       -- сырой payload вебхука, для разбора споров
  created_at          timestamptz not null default now()
);

create index if not exists payments_order_idx on public.payments (order_id);

-- Один и тот же вебхук может прийти дважды (ретраи платёжной системы).
-- Уникальный индекс не даст обработать платёж повторно.
create unique index if not exists payments_provider_uniq
  on public.payments (provider, provider_payment_id)
  where provider_payment_id is not null;

-- ── отправления ───────────────────────────────────────────────────────
create table if not exists public.shipments (
  id              uuid primary key default gen_random_uuid(),
  order_id        uuid not null references public.orders(id) on delete cascade,
  carrier         text not null default 'CDEK',
  carrier_uuid    text,                      -- uuid заказа в CDEK
  tracking_number text,                      -- появляется не сразу, поэтому nullable
  status          text not null default 'CREATED',
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index if not exists shipments_order_idx on public.shipments (order_id);
create index if not exists shipments_track_idx on public.shipments (tracking_number);

-- ── история статусов доставки ─────────────────────────────────────────
create table if not exists public.shipment_events (
  id          uuid primary key default gen_random_uuid(),
  shipment_id uuid not null references public.shipments(id) on delete cascade,
  code        text,                          -- код статуса CDEK
  status      text not null,                 -- человекочитаемый статус
  comment     text,
  occurred_at timestamptz not null default now(),
  raw         jsonb,
  created_at  timestamptz not null default now()
);

create index if not exists shipment_events_shipment_idx
  on public.shipment_events (shipment_id, occurred_at desc);

-- ── updated_at сам по себе ────────────────────────────────────────────
create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists orders_touch on public.orders;
create trigger orders_touch before update on public.orders
  for each row execute function public.touch_updated_at();

drop trigger if exists shipments_touch on public.shipments;
create trigger shipments_touch before update on public.shipments
  for each row execute function public.touch_updated_at();

-- ── RLS: наружу закрыто всё ───────────────────────────────────────────
-- Политик не создаём намеренно. anon и authenticated не получат ни строки.
-- service_role (backend) RLS обходит — писать и читать может только он.
alter table public.users           enable row level security;
alter table public.orders          enable row level security;
alter table public.order_items     enable row level security;
alter table public.payments        enable row level security;
alter table public.shipments       enable row level security;
alter table public.shipment_events enable row level security;

-- ── страница заказа по секретной ссылке ───────────────────────────────
-- Единственная дверь наружу. Отдаёт заказ, позиции и историю доставки
-- по токену из ссылки. Внутренние поля (raw payload платежа, id платежа,
-- телефон целиком) наружу не уходят.
create or replace function public.order_by_token(p_token text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  o public.orders;
  result jsonb;
begin
  -- Пустой или короткий токен не ищем вовсе.
  if p_token is null or length(p_token) < 32 then
    return null;
  end if;

  select * into o from public.orders where secure_token = p_token;
  if not found then
    return null;
  end if;

  select jsonb_build_object(
    'order_no',        o.order_no,
    'status',          o.status,
    'created_at',      o.created_at,
    'paid_at',         o.paid_at,
    'customer_name',   o.customer_name,
    -- Телефон маскируем: ссылку могут переслать в чат.
    'phone_masked',    regexp_replace(o.phone, '.(?=.{4})', '*', 'g'),
    'delivery_method', o.delivery_method,
    'city',            o.city,
    'address',         o.address,
    'currency',        o.currency,
    'subtotal',        o.subtotal,
    'discount',        o.discount,
    'total',           o.total,
    'items', coalesce((
      select jsonb_agg(jsonb_build_object(
        'title', i.title, 'fit', i.fit, 'size', i.size,
        'color', i.color, 'qty', i.qty, 'unit_price', i.unit_price
      ) order by i.created_at)
      from public.order_items i where i.order_id = o.id
    ), '[]'::jsonb),
    'shipment', (
      select jsonb_build_object(
        'carrier',         s.carrier,
        'tracking_number', s.tracking_number,
        'status',          s.status,
        'events', coalesce((
          select jsonb_agg(jsonb_build_object(
            'status', e.status, 'comment', e.comment, 'occurred_at', e.occurred_at
          ) order by e.occurred_at)
          from public.shipment_events e where e.shipment_id = s.id
        ), '[]'::jsonb)
      )
      from public.shipments s where s.order_id = o.id
      order by s.created_at desc limit 1
    )
  ) into result;

  return result;
end;
$$;

-- Вызывать функцию можно из браузера, но она отдаёт только тот заказ,
-- к которому знаешь токен. Прямого доступа к таблицам это не даёт.
revoke all on function public.order_by_token(text) from public;
grant execute on function public.order_by_token(text) to anon, authenticated;

-- ─────────────────────────────────────────────────────────────────────────
-- ЧЕГО ЗДЕСЬ НАМЕРЕННО НЕТ
--
-- 1. Таблицы товаров. Каталог сейчас живёт в коде (src/data.js), поэтому
--    цену в заказ кладёт браузер. Это нормально для витрины, но перед
--    приёмом настоящих денег backend обязан пересчитывать сумму сам —
--    иначе её можно подменить через консоль браузера. Варианта два:
--    держать прайс в backend или завести таблицу products и считать по ней.
--
-- 2. Политик RLS для anon. Это не забывчивость: по ТЗ пишет только backend
--    под service_role. Если открыть запись из браузера, любой сможет
--    создать заказ с произвольной суммой и статусом PAID.
--
-- 3. Логики вебхуков. SQL хранит данные, но не ходит в CDEK и не слушает
--    платёжную систему. Это код backend: POST /api/payment/webhook,
--    POST /api/cdek/create, POST /api/cdek/webhook.
-- ─────────────────────────────────────────────────────────────────────────
