// Каталог + словарь переводов. Всё в одном месте, чтобы легко править.

// Рынок дизайна: по нему делим каталог на русские и казахские принты.
export const MARKETS = {
  ru: { ru: 'Русский', kk: 'Орысша', color: '#4f8cff' },
  kk: { ru: 'Қазақша', kk: 'Қазақша', color: '#00b894' },
}

// Каждый товар — фотомокап в белом и чёрном варианте (public/tees).
export const PRODUCTS = [
  {
    id: 'arak',
    market: 'kk',
    base: 9900,
    color: '#e9e7e2',
    photos: { white: '/tees/arak-w.png', black: '/tees/arak-b.png' },
    ru: { title: 'Арақ ішу', sub: 'Бухать — это не спорт' },
    kk: { title: 'Арақ ішу', sub: 'Бұл спорт емес — денсаулық керек' },
  },
  {
    id: 'magan40',
    market: 'kk',
    base: 9900,
    color: '#e9e7e2',
    photos: { white: '/tees/magan40-w.png', black: '/tees/magan40-b.png' },
    ru: { title: 'Маған 40 емес', sub: 'Мне не 40' },
    kk: { title: 'Маған 40 емес', sub: 'Жасым туралы айтпашы' },
  },
  {
    id: 'eskifoto',
    market: 'kk',
    base: 8900,
    color: '#e9e7e2',
    photos: { white: '/tees/eskifoto-w.png', black: '/tees/eskifoto-b.png' },
    ru: { title: 'Менің ескі фоткам', sub: 'Моя старая фотка' },
    kk: { title: 'Менің ескі фоткам', sub: 'Ол — ескі, мен — сол баяғымын' },
  },
  {
    id: 'sagat',
    market: 'kk',
    base: 9900,
    color: '#e9e7e2',
    photos: { white: '/tees/sagat-w.png', black: '/tees/sagat-b.png' },
    ru: { title: 'Сағатым тұрып қалды', sub: 'Мои часы встали' },
    kk: { title: 'Сағатым тұрып қалды', sub: 'Кешігуімнің ресми себебі' },
  },
  {
    id: 'kyzym',
    market: 'kk',
    base: 9900,
    color: '#e9e7e2',
    photos: { white: '/tees/kyzym-w.png', black: '/tees/kyzym-b.png' },
    ru: { title: 'Қызым жоқ', sub: 'У меня нет дочки' },
    kk: { title: 'Қызым жоқ', sub: 'Сондықтан тыныш ұйықтаймын' },
  },
  {
    id: 'buhat',
    market: 'ru',
    base: 9900,
    color: '#e9e7e2',
    photos: { white: '/tees/buhat-w.png', black: '/tees/buhat-b.png' },
    ru: { title: 'Бухать!', sub: 'Это вам не спортом заниматься' },
    kk: { title: 'Бухать!', sub: 'Классика жанра' },
  },
  {
    id: 'buhatsport',
    market: 'ru',
    base: 9900,
    color: '#e9e7e2',
    photos: { white: '/tees/buhatsport-w.png', black: '/tees/buhatsport-b.png' },
    ru: { title: 'Бухать — не спорт', sub: 'Тут здоровье нужно' },
    kk: { title: 'Бухать — не спорт', sub: 'Оправдание чемпиона' },
  },
  {
    id: 'volosy',
    market: 'ru',
    base: 8900,
    color: '#e9e7e2',
    photos: { white: '/tees/volosy-w.png', black: '/tees/volosy-b.png' },
    ru: { title: 'Волосы', sub: 'Были. Ушли. Не вернулись.' },
    kk: { title: 'Волосы', sub: 'Мемориальная футболка' },
  },
  {
    id: 'luchshe',
    market: 'ru',
    base: 9900,
    color: '#e9e7e2',
    photos: { white: '/tees/luchshe-w.png', black: '/tees/luchshe-b.png' },
    ru: { title: 'Лучше некуда', sub: 'Сарказм в чистом виде' },
    kk: { title: 'Лучше некуда', sub: 'Ответ на «как дела»' },
  },
  {
    id: 'ne40',
    market: 'ru',
    base: 9900,
    color: '#e9e7e2',
    photos: { white: '/tees/ne40-w.png', black: '/tees/ne40-b.png' },
    ru: { title: 'Мне не 40', sub: 'Мне восемнадцать с опытом' },
    kk: { title: 'Мне не 40', sub: 'Отрицание возраста' },
  },
  {
    id: 'starayafoto',
    market: 'ru',
    base: 8900,
    color: '#e9e7e2',
    photos: { white: '/tees/starayafoto-w.png', black: '/tees/starayafoto-b.png' },
    ru: { title: 'Моя старая фотка', sub: 'Раньше было лучше' },
    kk: { title: 'Моя старая фотка', sub: 'Ностальгия на груди' },
  },
  {
    id: 'napohu',
    market: 'ru',
    base: 10900,
    color: '#e9e7e2',
    photos: { white: '/tees/napohu-w.png', black: '/tees/napohu-b.png' },
    ru: { title: 'На всё по…', sub: 'Философия спокойствия' },
    kk: { title: 'На всё по…', sub: 'Для дзен-мастеров' },
  },
  {
    id: 'rabota',
    market: 'ru',
    base: 10900,
    color: '#e9e7e2',
    photos: { white: '/tees/rabota-w.png', black: '/tees/rabota-b.png' },
    ru: { title: 'На работе…', sub: 'Понедельник как он есть' },
    kk: { title: 'На работе…', sub: 'Только для взрослых' },
  },
  {
    id: 'perestat',
    market: 'ru',
    base: 9900,
    color: '#e9e7e2',
    photos: { white: '/tees/perestat-w.png', black: '/tees/perestat-b.png' },
    ru: { title: 'Перестать выёживаться', sub: 'Список дел на год' },
    kk: { title: 'Перестать выёживаться', sub: 'Мотивация здорового человека' },
  },
  {
    id: 'pohudenie',
    market: 'ru',
    base: 8900,
    color: '#e9e7e2',
    photos: { white: '/tees/pohudenie-w.png', black: '/tees/pohudenie-b.png' },
    ru: { title: 'Похудение', sub: 'Начну с понедельника' },
    kk: { title: 'Похудение', sub: 'Вечный план' },
  },
  {
    id: 'pochemuinet',
    market: 'ru',
    base: 9900,
    color: '#e9e7e2',
    photos: { white: '/tees/pochemuinet-w.png', black: '/tees/pochemuinet-b.png' },
    ru: { title: 'Почему и нет', sub: 'Ответ на любой вопрос' },
    kk: { title: 'Почему и нет', sub: 'Девиз оптимиста' },
  },
  {
    id: 'netdevushki',
    market: 'ru',
    base: 9900,
    color: '#e9e7e2',
    photos: { white: '/tees/netdevushki-w.png', black: '/tees/netdevushki-b.png' },
    ru: { title: 'Почему нет девушки', sub: 'Список причин на спине' },
    kk: { title: 'Почему нет девушки', sub: 'Честная футболка' },
  },
  {
    id: 'robin',
    market: 'ru',
    base: 11900,
    color: '#e9e7e2',
    photos: { white: '/tees/robin-w.png', black: '/tees/robin-b.png' },
    ru: { title: 'Робин Гуд', sub: 'Отбирал у богатых. Уважаем.' },
    kk: { title: 'Робин Гуд', sub: 'Народный герой' },
  },
  {
    id: 'skolzkiy',
    market: 'ru',
    base: 9900,
    color: '#e9e7e2',
    photos: { white: '/tees/skolzkiy-w.png', black: '/tees/skolzkiy-b.png' },
    ru: { title: 'Скользкий тип', sub: 'Выкрутится из любой ситуации' },
    kk: { title: 'Скользкий тип', sub: 'Комплимент или нет' },
  },
  {
    id: 'chasy',
    market: 'ru',
    base: 9900,
    color: '#e9e7e2',
    photos: { white: '/tees/chasy-w.png', black: '/tees/chasy-b.png' },
    ru: { title: 'Часы встали', sub: 'Опять не моя вина' },
    kk: { title: 'Часы встали', sub: 'Универсальная отмазка' },
  },
]

export const SIZES = ['S', 'M', 'L', 'XL', 'XXL']

// Цена зависит от размера: большие требуют больше ткани.
export const SIZE_EXTRA = { S: 0, M: 0, L: 0, XL: 1000, XXL: 1500 }
export const priceFor = (product, size) => (product.base ?? 0) + (SIZE_EXTRA[size] ?? 0)

/* ── Конструктор ── */
export const CUSTOM_PRICE = 15900

// Только белая и чёрная ткань — как в настоящей печати.
export const CUSTOM_COLORS = [
  { id: 'white', fabric: '#f0efec', ink: '#141414' },
  { id: 'black', fabric: '#141414', ink: '#ffffff' },
]

export const INK_COLORS = ['#141414', '#ffffff']

// Заготовки: с чистого листа начинать неудобно.
export const TEMPLATES = [
  {
    id: 'slogan',
    ru: 'Слоган', kk: 'Ұран',
    patch: { text: 'ЖИЗНЬ\nБОЛЬ', font: 'display', bold: true, upper: true, textSize: 1.6, textWidth: 100, textPos: { x: 0, y: 0 }, textRotate: 0, outline: false },
  },
  {
    id: 'diagonal',
    ru: 'По диагонали', kk: 'Қиғаш',
    patch: { text: 'ПОЗЖЕ', font: 'narrow', bold: true, upper: true, textSize: 2.2, textWidth: 118, textPos: { x: 0, y: 6 }, textRotate: -14, outline: true },
  },
  {
    id: 'quote',
    ru: 'Цитата', kk: 'Дәйексөз',
    patch: { text: '«я в порядке»\n— я, не в порядке', font: 'serif', bold: false, italic: true, upper: false, textSize: 1.1, textWidth: 108, textPos: { x: 0, y: 4 }, textRotate: 0, outline: false },
  },
  {
    id: 'terminal',
    ru: 'Терминал', kk: 'Терминал',
    patch: { text: '> sudo make me\n  a sandwich', font: 'mono', bold: true, italic: false, upper: false, textSize: 1.15, textWidth: 112, textPos: { x: 0, y: 2 }, textRotate: 0, outline: false },
  },
]

// Системные шрифты + два уже подключённых: ничего лишнего не качаем.
export const FONTS = [
  { id: 'display', label: 'Unbounded', css: "'Unbounded', sans-serif" },
  { id: 'grotesk', label: 'Grotesk', css: "'Space Grotesk', sans-serif" },
  { id: 'serif', label: 'Serif', css: "Georgia, 'Times New Roman', serif" },
  { id: 'mono', label: 'Mono', css: "'Courier New', monospace" },
  { id: 'narrow', label: 'Impact', css: "Impact, 'Arial Narrow', sans-serif" },
]

export const T = {
  ru: {
    lang: 'RU',
    nav_shop: 'Каталог',
    nav_how: 'Как это работает',
    nav_wallet: 'Кошелёк',
    nav_admin: 'Админка',
    tagline: 'Футболки, за которые с тобой заговорят в автобусе',
    hero_1: 'ПРИОБРЁЛ',
    hero_2: 'РАССМЕШИЛ',
    hero_3: 'ПОСМЕЯЛСЯ',
    hero_sub: 'Мемные футболки ручной печати. Каждый принт проверен на живых людях: если никто не улыбнулся — принт в мусор.',
    cta_shop: 'Смотреть каталог',
    stat_1: 'принтов в тираже',
    stat_2: 'смеха на складе',
    stat_3: 'дня доставка по РК',
    catalog_title: 'КАТАЛОГ',
    catalog_sub: 'Свежие принты и заготовки под свой дизайн',
    filter_all: 'Все',
    lol_meter: 'ЛОЛ-метр',
    add: 'В корзину',
    added: 'Добавлено!',
    size: 'Размер',
    color: 'Цвет футболки',
    c_white: 'Белая',
    c_black: 'Чёрная',
    cart: 'Корзина',
    cart_empty: 'Пусто. Совсем. Как мой календарь.',
    total: 'Итого',
    checkout: 'Оплатить кошельком',
    wallet: 'funymems Wallet',
    balance: 'Баланс',
    coins: 'funymems-коины',
    topup: 'Пополнить',
    cashback: 'Кэшбэк 7% коинами с каждой покупки',
    pay_ok: 'Оплачено. Смех отгружен',
    pay_fail: 'На кошельке не хватает денег',
    how_title: 'КАК ЭТО РАБОТАЕТ',
    how_1_t: 'Выбираешь мем',
    how_1_d: 'Или собираешь свой принт в конструкторе — текст, фото, обе стороны.',
    how_2_t: 'Платишь картой или кошельком',
    how_2_d: 'С кошелька возвращаем 7% коинами. Без регистрации.',
    how_3_t: 'Носишь',
    how_3_d: 'Незнакомцы начинают разговор. Это побочный эффект, мы предупредили.',
    drop_title: 'ДРОП НЕДЕЛИ ЗАКАНЧИВАЕТСЯ ЧЕРЕЗ',
    d: 'д', h: 'ч', m: 'м', s: 'с',
    footer: 'Сделано в Казахстане. Смех не возвращается.',
    rarity_label: 'Редкость',
    remove: 'Убрать',
    added_coins: 'коинов начислено',
    topup_added: 'Кошелёк пополнен',

    /* кошелёк и оплата */
    account: 'Кошелёк',
    pay_method: 'Чем платим',
    pay_card: 'Карта',
    pay_wallet: 'Кошелёк',
    card_demo: 'Демо-карта, деньги не списываются',
    promo_ph: 'Промокод',
    apply: 'Применить',
    discount: 'Скидка',
    promo_bad: 'Такого кода нет',
    promo_on: 'Промокод применён',
    ship_title: 'Куда доставить',
    f_name: 'Имя',
    f_phone: 'Телефон',
    f_city: 'Город',
    f_address: 'Адрес: улица, дом, кв.',
    fill_ship: 'Заполни имя и телефон',
    authorizing: 'Авторизация карты…',
    theme_dark: 'Тёмная тема',
    theme_light: 'Светлая тема',
    tab_wallet: 'Кошелёк',
    tab_orders: 'Заказы',
    tab_fav: 'Избранное',
    no_orders: 'Заказов пока нет. Непорядок.',
    no_fav: 'Пока ничего не понравилось',
    order_no: 'Заказ',
    member_since: 'С нами с',
    orders_count: 'заказов',
    spent: 'потрачено',
    pick_emoji: 'Аватар',
    save: 'Сохранить',
    saved: 'Сохранено ✓',
    to_fav: 'В избранное',
    processing: 'Секунду…',

    /* конструктор */
    designer: 'Свой дизайн',
    designer_open: 'Собрать свою',
    designer_title: 'КОНСТРУКТОР',
    designer_sub: 'Пиши что хочешь, кидай своё фото — напечатаем',
    d_fabric: 'Цвет футболки',
    d_text: 'Текст на футболке',
    d_text_ph: 'НАПИШИ\nЧТО-НИБУДЬ',
    d_text_hint: 'Enter — новая строка',
    d_ink: 'Цвет текста',
    d_size: 'Размер текста',
    d_photo: 'Своё фото',
    d_photo_add: 'Загрузить картинку',
    d_photo_del: 'Убрать картинку',
    d_photo_size: 'Размер картинки',
    d_font: 'Шрифт',
    d_style: 'Начертание',
    d_bold: 'Жирный',
    d_italic: 'Курсив',
    d_upper: 'КАПСОМ',
    d_align: 'Выравнивание',
    d_width: 'Ширина блока текста',
    d_drag: 'Перетаскивай текст и картинку; за палочки по бокам — ширина',
    d_tab_tpl: 'Шаблоны',
    d_tab_text: 'Текст',
    d_tab_photo: 'Фото',
    d_tab_shirt: 'Футболка',
    d_side: 'Сторона',
    d_front: 'Перёд',
    d_back: 'Спина',
    d_rotate: 'Поворот',
    d_outline: 'Обводка',
    d_undo: 'Отменить',
    d_redo: 'Вернуть',
    d_tpl_hint: 'Заготовка заменит текст на выбранной стороне',
    d_side_empty: 'На этой стороне пусто',
    d_both: 'перёд + спина',
    d_center: 'По центру',
    d_layer: 'Слой',
    d_reset: 'Сбросить',
    d_empty: 'Добавь текст или картинку',
    d_too_big: 'Файл больше 8 МБ — возьми поменьше',
    d_bad_file: 'Это не картинка',
    d_added: 'Твой дизайн в корзине',
    /* ошибки */
    err_auth_required: 'Сначала войди в аккаунт',
    err_bad_creds: 'Неверная почта или пароль',
    err_user_exists: 'Такая почта уже занята',
    err_weak_pass: 'Пароль минимум 6 символов',
    err_not_confirmed: 'Почта не подтверждена — проверь письмо',
    err_rate_limit: 'Слишком много попыток. Подожди минуту.',
    err_network: 'Нет связи с сервером',
    err_generic: 'Что-то пошло не так',
    err_fill: 'Заполни все поля',
    not_setup: 'Supabase не подключён — авторизация выключена. См. README.',
  },
  kk: {
    lang: 'ҚАЗ',
    nav_shop: 'Каталог',
    nav_how: 'Қалай жұмыс істейді',
    nav_wallet: 'Әмиян',
    nav_admin: 'Әкімші',
    tagline: 'Автобуста сізбен сөйлесе бастайтын футболкалар',
    hero_1: 'САТЫП АЛДЫМ',
    hero_2: 'КҮЛДІРДІМ',
    hero_3: 'КҮЛДІМ',
    hero_sub: 'Қолмен басылған мем футболкалар. Әр принт тірі адамдарға тексерілген: ешкім күлмесе — принт қоқысқа.',
    cta_shop: 'Каталогты көру',
    stat_1: 'принт таралымда',
    stat_2: 'күлкі қоймада',
    stat_3: 'күнде ҚР бойынша жеткізу',
    catalog_title: 'КАТАЛОГ',
    catalog_sub: 'Жаңа принттер және өз дизайныңа дайындамалар',
    filter_all: 'Барлығы',
    lol_meter: 'КҮЛКІ-метр',
    add: 'Себетке',
    added: 'Қосылды!',
    size: 'Өлшем',
    color: 'Футболка түсі',
    c_white: 'Ақ',
    c_black: 'Қара',
    cart: 'Себет',
    cart_empty: 'Бос. Мүлдем. Күнтізбем сияқты.',
    total: 'Жиыны',
    checkout: 'Әмиянмен төлеу',
    wallet: 'funymems Wallet',
    balance: 'Баланс',
    coins: 'funymems-коин',
    topup: 'Толтыру',
    cashback: 'Әр сатып алудан 7% коин кэшбэк',
    pay_ok: 'Төленді. Күлкі жөнелтілді',
    pay_fail: 'Әмияндағы қаражат жетпейді',
    how_title: 'ҚАЛАЙ ЖҰМЫС ІСТЕЙДІ',
    how_1_t: 'Мем таңдайсың',
    how_1_d: 'Немесе конструкторда өз принтіңді жинайсың — мәтін, сурет, екі жағы.',
    how_2_t: 'Картамен не әмиянмен төлейсің',
    how_2_d: 'Әмияннан 7% коин қайтарамыз. Тіркелусіз.',
    how_3_t: 'Киесің',
    how_3_d: 'Бейтаныс адамдар сөз бастайды. Бұл жанама әсер, ескерттік.',
    drop_title: 'АПТА ДРОБЫ АЯҚТАЛАДЫ',
    d: 'к', h: 'сағ', m: 'мин', s: 'сек',
    footer: 'Қазақстанда жасалған. Күлкі қайтарылмайды.',
    rarity_label: 'Сиректігі',
    remove: 'Алып тастау',
    added_coins: 'коин есептелді',
    topup_added: 'Әмиян толтырылды',

    /* әмиян және төлем */
    account: 'Әмиян',
    pay_method: 'Немен төлейміз',
    pay_card: 'Карта',
    pay_wallet: 'Әмиян',
    card_demo: 'Демо-карта, ақша шешілмейді',
    promo_ph: 'Промокод',
    apply: 'Қолдану',
    discount: 'Жеңілдік',
    promo_bad: 'Мұндай код жоқ',
    promo_on: 'Промокод қолданылды',
    ship_title: 'Қайда жеткіземіз',
    f_name: 'Аты',
    f_phone: 'Телефон',
    f_city: 'Қала',
    f_address: 'Мекенжай: көше, үй, пәтер',
    fill_ship: 'Аты мен телефонды толтыр',
    authorizing: 'Карта авторизациясы…',
    theme_dark: 'Қараңғы тақырып',
    theme_light: 'Жарық тақырып',
    tab_wallet: 'Әмиян',
    tab_orders: 'Тапсырыстар',
    tab_fav: 'Таңдаулылар',
    no_orders: 'Әзірге тапсырыс жоқ. Дұрыс емес.',
    no_fav: 'Әзірге ештеңе ұнаған жоқ',
    order_no: 'Тапсырыс',
    member_since: 'Бізбен бірге',
    orders_count: 'тапсырыс',
    spent: 'жұмсалды',
    pick_emoji: 'Аватар',
    save: 'Сақтау',
    saved: 'Сақталды ✓',
    to_fav: 'Таңдаулыға',
    processing: 'Бір сәт…',

    /* конструктор */
    designer: 'Өз дизайным',
    designer_open: 'Өзің жаса',
    designer_title: 'КОНСТРУКТОР',
    designer_sub: 'Не қаласаң жаз, өз суретіңді жібер — басып береміз',
    d_fabric: 'Футболка түсі',
    d_text: 'Футболкадағы мәтін',
    d_text_ph: 'БІРДЕҢЕ\nЖАЗ',
    d_text_hint: 'Enter — жаңа жол',
    d_ink: 'Мәтін түсі',
    d_size: 'Мәтін өлшемі',
    d_photo: 'Өз суретің',
    d_photo_add: 'Сурет жүктеу',
    d_photo_del: 'Суретті алып тастау',
    d_photo_size: 'Сурет өлшемі',
    d_font: 'Қаріп',
    d_style: 'Стилі',
    d_bold: 'Қалың',
    d_italic: 'Көлбеу',
    d_upper: 'БАС ӘРІП',
    d_align: 'Туралау',
    d_width: 'Мәтін блогының ені',
    d_drag: 'Мәтін мен суретті сүйре; бүйірдегі таяқшалармен енін өзгерт',
    d_tab_tpl: 'Дайын',
    d_tab_text: 'Мәтін',
    d_tab_photo: 'Сурет',
    d_tab_shirt: 'Футболка',
    d_side: 'Жағы',
    d_front: 'Алды',
    d_back: 'Арты',
    d_rotate: 'Бұрылыс',
    d_outline: 'Контур',
    d_undo: 'Болдырмау',
    d_redo: 'Қайтару',
    d_tpl_hint: 'Дайындама таңдалған жақтағы мәтінді ауыстырады',
    d_side_empty: 'Бұл жақта бос',
    d_both: 'алды + арты',
    d_center: 'Ортаға',
    d_layer: 'Қабат',
    d_reset: 'Тазалау',
    d_empty: 'Мәтін не сурет қос',
    d_too_big: 'Файл 8 МБ-тан үлкен — кішірегін ал',
    d_bad_file: 'Бұл сурет емес',
    d_added: 'Дизайның себетте',
    /* ошибки */
    err_auth_required: 'Алдымен аккаунтқа кір',
    err_bad_creds: 'Пошта не құпиясөз қате',
    err_user_exists: 'Бұл пошта тіркелген',
    err_weak_pass: 'Құпиясөз кемінде 6 таңба',
    err_not_confirmed: 'Пошта расталмаған — хатты тексер',
    err_rate_limit: 'Тым көп әрекет. Бір минут күт.',
    err_network: 'Сервермен байланыс жоқ',
    err_generic: 'Бірдеңе дұрыс болмады',
    err_fill: 'Барлық өрісті толтыр',
    not_setup: 'Supabase қосылмаған — авторизация өшірулі. README қара.',
  },
}

export const fmt = (n) => new Intl.NumberFormat('ru-RU').format(n) + ' ₸'
