// Каталог + словарь переводов. Всё в одном месте, чтобы легко править.

export const RARITY = {
  common: { ru: 'Обычный', kk: 'Кәдімгі', color: '#9aa0a6' },
  rare: { ru: 'Редкий', kk: 'Сирек', color: '#4f8cff' },
  legendary: { ru: 'Легендарный', kk: 'Аңызға айналған', color: '#ff2e88' },
}

// art — параметры для генеративного принта (рисуем SVG, а не грузим картинки)
// photo — если указан, вместо рисованной футболки показывается фотография из /public
export const PRODUCTS = [
  {
    id: 'your-design',
    price: 15900,
    rarity: 'legendary',
    lol: 100,
    color: '#e9e9e7',
    ink: '#111',
    photo: '/tee-photo.jpg',
    ru: { title: 'Твой дизайн', print: '', sub: 'Присылаешь свой мем — печатаем его' },
    kk: { title: 'Сенің дизайның', print: '', sub: 'Өз мемінді жібер — біз басып береміз' },
  },
  {
    id: 'nugget',
    price: 13900,
    rarity: 'legendary',
    lol: 98,
    color: '#141414',
    ink: '#f5f0e8',
    photo: '/tee-nugget.jpg',
    ru: { title: 'Наггетс-мужик', print: '', sub: 'Он всё видел. Он ничего не скажет.' },
    kk: { title: 'Наггетс-ағай', print: '', sub: 'Ол бәрін көрген. Ештеңе айтпайды.' },
  },
  {
    id: 'nice-try',
    price: 14900,
    rarity: 'rare',
    lol: 88,
    color: '#0d0d0d',
    ink: '#f5f0e8',
    photo: '/tee-diddy.jpg',
    ru: { title: 'Nice Try', print: '', sub: 'Классика чёрного цвета' },
    kk: { title: 'Nice Try', print: '', sub: 'Қара түсті классика' },
  },
  {
    id: 'noutbuk',
    price: 11900,
    rarity: 'rare',
    lol: 87,
    color: '#f5f0e8',
    ink: '#111',
    art: 'face-dead',
    ru: { title: 'Ноутбук грузится. Я тоже.', print: 'ЗАГРУЗКА…\n1%', sub: 'Для тех, кто просыпается дольше Windows' },
    kk: { title: 'Ноутбук жүктелуде. Мен де.', print: 'ЖҮКТЕЛУДЕ…\n1%', sub: 'Windows-тан баяу оянатындарға' },
  },
  {
    id: 'shai',
    price: 12900,
    rarity: 'legendary',
    lol: 96,
    color: '#111',
    ink: '#ffe600',
    art: 'cup',
    ru: { title: 'Шай ішесің бе?', print: 'ШАЙ\nІШЕСІҢ БЕ?', sub: 'Вопрос, на который нет ответа «нет»' },
    kk: { title: 'Шай ішесің бе?', print: 'ШАЙ\nІШЕСІҢ БЕ?', sub: '«Жоқ» деген жауабы жоқ сұрақ' },
  },
  {
    id: 'motivation',
    price: 10900,
    rarity: 'common',
    lol: 74,
    color: '#0a1f3d',
    ink: '#00ff9d',
    art: 'glitch',
    ru: { title: 'Error 404', print: 'ERROR 404\nМОТИВАЦИЯ\nНЕ НАЙДЕНА', sub: 'Перезагрузка не помогает' },
    kk: { title: 'Error 404', print: 'ERROR 404\nЫНТА\nТАБЫЛМАДЫ', sub: 'Қайта қосу көмектеспейді' },
  },
  {
    id: 'baursak',
    price: 13900,
    rarity: 'legendary',
    lol: 99,
    color: '#ffb703',
    ink: '#3a1d00',
    art: 'baursak',
    ru: { title: 'Baursak Enjoyer', print: 'BAURSAK\nENJOYER', sub: 'Съел 40 штук и не жалею' },
    kk: { title: 'Baursak Enjoyer', print: 'BAURSAK\nENJOYER', sub: '40 дана жедім, өкінбеймін' },
  },
  {
    id: 'pyat-minut',
    price: 11900,
    rarity: 'rare',
    lol: 91,
    color: '#f2f2f2',
    ink: '#e63946',
    art: 'clock',
    ru: { title: 'Я в пути (нет)', print: '«5 МИНУТ»\n= 3 ЧАСА', sub: 'Национальная единица времени' },
    kk: { title: 'Жолдамын (жоқ)', print: '«5 МИНӨТ»\n= 3 САҒАТ', sub: 'Ұлттық уақыт өлшемі' },
  },
  {
    id: 'kot',
    price: 12400,
    rarity: 'rare',
    lol: 83,
    color: '#1b1b1b',
    ink: '#f5f0e8',
    art: 'cat',
    ru: { title: 'Кот съел мой дедлайн', print: 'МОЙ КОТ\nСЪЕЛ\nДЕДЛАЙН', sub: 'Отмазка премиум-класса' },
    kk: { title: 'Мысығым дедлайнды жеп қойды', print: 'МЫСЫҒЫМ\nДЕДЛАЙНДЫ\nЖЕП ҚОЙДЫ', sub: 'Премиум-сылтау' },
  },
  {
    id: 'ne-zvoni',
    price: 9900,
    rarity: 'common',
    lol: 78,
    color: '#e8e2d9',
    ink: '#111',
    art: 'phone',
    ru: { title: 'Не звони. Пиши.', print: 'НЕ ЗВОНИ\nПИШИ', sub: 'Манифест интроверта' },
    kk: { title: 'Қоңырау шалма. Жаз.', print: 'ҚОҢЫРАУ\nШАЛМА\nЖАЗ', sub: 'Интроверт манифесі' },
  },
  {
    id: 'ne-spal',
    price: 10900,
    rarity: 'common',
    lol: 80,
    color: '#6a4c93',
    ink: '#ffe600',
    art: 'eyes',
    ru: { title: 'Я не спал, я моргал', print: 'Я НЕ СПАЛ\nЯ ДОЛГО\nМОРГАЛ', sub: 'Для совещаний в 9 утра' },
    kk: { title: 'Ұйықтаған жоқпын, көз ілдім', print: 'ҰЙЫҚТАҒАН\nЖОҚПЫН\nКӨЗ ІЛДІМ', sub: 'Таңғы 9-дағы жиналысқа' },
  },
  {
    id: 'mama-tv',
    price: 14900,
    rarity: 'legendary',
    lol: 94,
    color: '#f5f0e8',
    ink: '#0057b7',
    art: 'tv',
    ru: { title: 'Мама, я в телевизоре', print: 'МАМА\nЯ В\nТЕЛЕВИЗОРЕ', sub: 'Слава пришла неожиданно' },
    kk: { title: 'Мама, мен теледидардамын', print: 'МАМА\nМЕН\nТЕЛЕДИДАРДАМЫН', sub: 'Даңқ күтпеген жерден келді' },
  },
  {
    id: 'peshkom',
    price: 9900,
    rarity: 'common',
    lol: 71,
    color: '#2d6a4f',
    ink: '#f5f0e8',
    art: 'walk',
    ru: { title: 'Спасибо, я пешком', print: 'СПАСИБО\nЯ ПЕШКОМ', sub: 'Когда назвали цену за такси' },
    kk: { title: 'Рахмет, жаяу барам', print: 'РАХМЕТ\nЖАЯУ\nБАРАМ', sub: 'Таксидің бағасын естігенде' },
  },
]

export const SIZES = ['S', 'M', 'L', 'XL', 'XXL']

/* ── Конструктор ── */
export const CUSTOM_PRICE = 15900

// Цвета ткани, доступные в конструкторе: [заливка, цвет текста по умолчанию]
export const CUSTOM_COLORS = [
  { id: 'white', fabric: '#f0efec', ink: '#111111' },
  { id: 'black', fabric: '#141414', ink: '#f5f0e8' },
  { id: 'acid', fabric: '#ffe600', ink: '#141414' },
  { id: 'pink', fabric: '#ff2e88', ink: '#ffffff' },
  { id: 'green', fabric: '#2d6a4f', ink: '#f5f0e8' },
  { id: 'blue', fabric: '#0a1f3d', ink: '#f5f0e8' },
]

export const INK_COLORS = ['#141414', '#f5f0e8', '#ffe600', '#ff2e88', '#00e5a0', '#e63946', '#4f8cff']

export const T = {
  ru: {
    lang: 'RU',
    nav_shop: 'Каталог',
    nav_how: 'Как это работает',
    nav_wallet: 'Кошелёк',
    tagline: 'Футболки, за которые с тобой заговорят в автобусе',
    hero_1: 'НАДЕЛ',
    hero_2: 'ФУТБОЛКУ',
    hero_3: 'ЗАСМЕЯЛСЯ',
    hero_sub: 'Мемные футболки ручной печати. Каждый принт проверен на живых людях: если никто не улыбнулся — принт в мусор.',
    cta_shop: 'Смотреть каталог',
    cta_random: 'Мне повезёт 🎲',
    stat_1: 'принтов в тираже',
    stat_2: 'смеха на складе',
    stat_3: 'дня доставка по РК',
    catalog_title: 'КАТАЛОГ',
    catalog_sub: 'Отсортировано по уровню ржача',
    filter_all: 'Все',
    lol_meter: 'ЛОЛ-метр',
    add: 'В корзину',
    added: 'Добавлено!',
    size: 'Размер',
    cart: 'Корзина',
    cart_empty: 'Пусто. Совсем. Как мой календарь.',
    total: 'Итого',
    checkout: 'Оплатить кошельком',
    wallet: 'ХЕХЕ Wallet',
    balance: 'Баланс',
    coins: 'ХЕХЕ-коины',
    topup: 'Пополнить',
    cashback: 'Кэшбэк 7% коинами с каждой покупки',
    pay_ok: 'Оплачено! Смех отгружен 📦',
    pay_fail: 'Не хватает денег на кошельке 😬',
    how_title: 'КАК ЭТО РАБОТАЕТ',
    how_1_t: 'Выбираешь мем',
    how_1_d: 'Смотришь на ЛОЛ-метр. Ниже 70 мы вообще не печатаем.',
    how_2_t: 'Платишь кошельком',
    how_2_d: 'Пополняешь ХЕХЕ Wallet, получаешь 7% коинами обратно.',
    how_3_t: 'Носишь',
    how_3_d: 'Незнакомцы начинают разговор. Это побочный эффект, мы предупредили.',
    drop_title: 'ДРОП НЕДЕЛИ ЗАКАНЧИВАЕТСЯ ЧЕРЕЗ',
    d: 'д', h: 'ч', m: 'м', s: 'с',
    footer: 'Сделано в Казахстане. Смех не возвращается.',
    rarity_label: 'Редкость',
    remove: 'Убрать',
    added_coins: 'коинов начислено',
    topup_added: 'Кошелёк пополнен',

    /* авторизация */
    login: 'Войти',
    signup: 'Регистрация',
    logout: 'Выйти',
    account: 'Кабинет',
    email: 'Почта',
    password: 'Пароль',
    name: 'Как тебя звать',
    name_ph: 'Ержан',
    google: 'Войти через Google',
    or: 'или',
    have_acc: 'Уже есть аккаунт?',
    no_acc: 'Нет аккаунта?',
    auth_title_in: 'С возвращением',
    auth_title_up: 'Заводим аккаунт',
    auth_sub_in: 'Кошелёк, заказы и избранное ждут',
    auth_sub_up: 'Дарим 25 000 ₸ на ХЕХЕ Wallet за регистрацию',
    confirm_sent: 'Проверь почту — там ссылка для подтверждения 📬',
    welcome: 'Салем',
    login_to_buy: 'Войди, чтобы оплатить',
    login_to_fav: 'Войди, чтобы сохранять избранное',
    tab_profile: 'Профиль',
    tab_orders: 'Заказы',
    tab_fav: 'Избранное',
    no_orders: 'Заказов пока нет. Непорядок.',
    no_fav: 'Пока ничего не понравилось 💔',
    order_no: 'Заказ',
    member_since: 'С нами с',
    orders_count: 'заказов',
    spent: 'потрачено',
    pick_emoji: 'Аватар',
    save: 'Сохранить',
    saved: 'Сохранено ✓',
    to_fav: 'В избранное',
    processing: 'Секунду…',

    /* конструктор */
    designer: 'Свой дизайн',
    designer_open: 'Собрать свою 🎨',
    designer_title: 'КОНСТРУКТОР',
    designer_sub: 'Пиши что хочешь, кидай своё фото — напечатаем',
    d_fabric: 'Цвет футболки',
    d_text: 'Текст на футболке',
    d_text_ph: 'НАПИШИ\nЧТО-НИБУДЬ',
    d_text_hint: 'Enter — новая строка',
    d_ink: 'Цвет текста',
    d_size: 'Размер текста',
    d_photo: 'Своё фото',
    d_photo_add: 'Загрузить картинку',
    d_photo_del: 'Убрать картинку',
    d_photo_size: 'Размер картинки',
    d_photo_first: 'Картинка сверху',
    d_reset: 'Сбросить',
    d_empty: 'Добавь текст или картинку',
    d_too_big: 'Файл больше 8 МБ — возьми поменьше',
    d_bad_file: 'Это не картинка',
    d_added: 'Твой дизайн в корзине 🎨',
    /* ошибки */
    err_auth_required: 'Сначала войди в аккаунт',
    err_bad_creds: 'Неверная почта или пароль',
    err_user_exists: 'Такая почта уже занята',
    err_weak_pass: 'Пароль минимум 6 символов',
    err_not_confirmed: 'Почта не подтверждена — проверь письмо',
    err_rate_limit: 'Слишком много попыток. Подожди минуту.',
    err_network: 'Нет связи с сервером',
    err_generic: 'Что-то пошло не так 🤷',
    err_fill: 'Заполни все поля',
    not_setup: 'Supabase не подключён — авторизация выключена. См. README.',
  },
  kk: {
    lang: 'ҚАЗ',
    nav_shop: 'Каталог',
    nav_how: 'Қалай жұмыс істейді',
    nav_wallet: 'Әмиян',
    tagline: 'Автобуста сізбен сөйлесе бастайтын футболкалар',
    hero_1: 'КИДІҢ',
    hero_2: 'ФУТБОЛКА',
    hero_3: 'КҮЛДІҢ',
    hero_sub: 'Қолмен басылған мем футболкалар. Әр принт тірі адамдарға тексерілген: ешкім күлмесе — принт қоқысқа.',
    cta_shop: 'Каталогты көру',
    cta_random: 'Маған сәттілік 🎲',
    stat_1: 'принт таралымда',
    stat_2: 'күлкі қоймада',
    stat_3: 'күнде ҚР бойынша жеткізу',
    catalog_title: 'КАТАЛОГ',
    catalog_sub: 'Күлкі деңгейі бойынша сұрыпталған',
    filter_all: 'Барлығы',
    lol_meter: 'КҮЛКІ-метр',
    add: 'Себетке',
    added: 'Қосылды!',
    size: 'Өлшем',
    cart: 'Себет',
    cart_empty: 'Бос. Мүлдем. Күнтізбем сияқты.',
    total: 'Жиыны',
    checkout: 'Әмиянмен төлеу',
    wallet: 'ХЕХЕ Wallet',
    balance: 'Баланс',
    coins: 'ХЕХЕ-коин',
    topup: 'Толтыру',
    cashback: 'Әр сатып алудан 7% коин кэшбэк',
    pay_ok: 'Төленді! Күлкі жөнелтілді 📦',
    pay_fail: 'Әмияндағы қаражат жетпейді 😬',
    how_title: 'ҚАЛАЙ ЖҰМЫС ІСТЕЙДІ',
    how_1_t: 'Мем таңдайсың',
    how_1_d: 'КҮЛКІ-метрге қара. 70-тен төмен принтті біз баспаймыз.',
    how_2_t: 'Әмиянмен төлейсің',
    how_2_d: 'ХЕХЕ Wallet-ті толтырасың, 7% коин қайтарасың.',
    how_3_t: 'Киесің',
    how_3_d: 'Бейтаныс адамдар сөз бастайды. Бұл жанама әсер, ескерттік.',
    drop_title: 'АПТА ДРОБЫ АЯҚТАЛАДЫ',
    d: 'к', h: 'сағ', m: 'мин', s: 'сек',
    footer: 'Қазақстанда жасалған. Күлкі қайтарылмайды.',
    rarity_label: 'Сиректігі',
    remove: 'Алып тастау',
    added_coins: 'коин есептелді',
    topup_added: 'Әмиян толтырылды',

    /* авторизация */
    login: 'Кіру',
    signup: 'Тіркелу',
    logout: 'Шығу',
    account: 'Кабинет',
    email: 'Пошта',
    password: 'Құпиясөз',
    name: 'Атың кім',
    name_ph: 'Ержан',
    google: 'Google арқылы кіру',
    or: 'немесе',
    have_acc: 'Аккаунтың бар ма?',
    no_acc: 'Аккаунтың жоқ па?',
    auth_title_in: 'Қайта қош келдің',
    auth_title_up: 'Аккаунт ашамыз',
    auth_sub_in: 'Әмиян, тапсырыстар мен таңдаулылар күтіп тұр',
    auth_sub_up: 'Тіркелгенге ХЕХЕ Wallet-ке 25 000 ₸ сыйға',
    confirm_sent: 'Поштаңды тексер — растау сілтемесі жіберілді 📬',
    welcome: 'Сәлем',
    login_to_buy: 'Төлеу үшін кір',
    login_to_fav: 'Таңдаулыға қосу үшін кір',
    tab_profile: 'Профиль',
    tab_orders: 'Тапсырыстар',
    tab_fav: 'Таңдаулылар',
    no_orders: 'Әзірге тапсырыс жоқ. Дұрыс емес.',
    no_fav: 'Әзірге ештеңе ұнаған жоқ 💔',
    order_no: 'Тапсырыс',
    member_since: 'Бізбен бірге',
    orders_count: 'тапсырыс',
    spent: 'жұмсалды',
    pick_emoji: 'Аватар',
    save: 'Сақтау',
    saved: 'Сақталды ✓',
    to_fav: 'Таңдаулыға',
    processing: 'Бір сәт…',

    /* конструктор */
    designer: 'Өз дизайным',
    designer_open: 'Өзің жаса 🎨',
    designer_title: 'КОНСТРУКТОР',
    designer_sub: 'Не қаласаң жаз, өз суретіңді жібер — басып береміз',
    d_fabric: 'Футболка түсі',
    d_text: 'Футболкадағы мәтін',
    d_text_ph: 'БІРДЕҢЕ\nЖАЗ',
    d_text_hint: 'Enter — жаңа жол',
    d_ink: 'Мәтін түсі',
    d_size: 'Мәтін өлшемі',
    d_photo: 'Өз суретің',
    d_photo_add: 'Сурет жүктеу',
    d_photo_del: 'Суретті алып тастау',
    d_photo_size: 'Сурет өлшемі',
    d_photo_first: 'Сурет жоғарыда',
    d_reset: 'Тазалау',
    d_empty: 'Мәтін не сурет қос',
    d_too_big: 'Файл 8 МБ-тан үлкен — кішірегін ал',
    d_bad_file: 'Бұл сурет емес',
    d_added: 'Дизайның себетте 🎨',
    /* ошибки */
    err_auth_required: 'Алдымен аккаунтқа кір',
    err_bad_creds: 'Пошта не құпиясөз қате',
    err_user_exists: 'Бұл пошта тіркелген',
    err_weak_pass: 'Құпиясөз кемінде 6 таңба',
    err_not_confirmed: 'Пошта расталмаған — хатты тексер',
    err_rate_limit: 'Тым көп әрекет. Бір минут күт.',
    err_network: 'Сервермен байланыс жоқ',
    err_generic: 'Бірдеңе дұрыс болмады 🤷',
    err_fill: 'Барлық өрісті толтыр',
    not_setup: 'Supabase қосылмаған — авторизация өшірулі. README қара.',
  },
}

export const fmt = (n) => new Intl.NumberFormat('ru-RU').format(n) + ' ₸'
